### ISSUE TITLE
Failed to install python-foreman release 0.3.1

### ISSUE THREAD

**Issue by avi3tal** [david-caro/python-foreman#44]
Moving to 0.3.1 broken my installation process.
I am using python-foreman as a requirement in my project.
When release 0.3.1 introduced my project installation suddenly start to break.

  Downloading python-foreman-0.3.1.linux-x86_64.tar.gz (159kB): 159kB downloaded
  Running setup.py (path:/tmp/pip-build-2K5JAs/python-foreman/setup.py) egg_info for package python-foreman
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-2K5JAs/python-foreman/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

IOError: [Errno 2] No such file or directory: '/tmp/pip-build-2K5JAs/python-foreman/setup.py'

**Comment by david-caro** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Will fix right away, strange error though

On May 10, 2015 5:22:39 PM GMT+02:00, avi tal <notifications@github.com> wrote:
>Moving to 0.3.1 broken my installation process.
>I am using python-foreman as a requirement in my project.
>When release 0.3.1 introduced my project installation suddenly start to
>break.
>
>Downloading python-foreman-0.3.1.linux-x86_64.tar.gz (159kB): 159kB
>downloaded
>Running setup.py (path:/tmp/pip-build-2K5JAs/python-foreman/setup.py)
>egg_info for package python-foreman
>    Traceback (most recent call last):
>      File "<string>", line 17, in <module>
>IOError: [Errno 2] No such file or directory:
>'/tmp/pip-build-2K5JAs/python-foreman/setup.py'
>    Complete output from command python setup.py egg_info:
>    Traceback (most recent call last):
>
>  File "<string>", line 17, in <module>
>
>IOError: [Errno 2] No such file or directory:
>'/tmp/pip-build-2K5JAs/python-foreman/setup.py'
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/david-caro/python-foreman/issues/44

- --
Sent from my Android device with K-9 Mail through Mykolab servers.
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQFLBAEBCgA1BQJVT3liLhxEYXZpZCBDYXJvIChSZWRIYXQga2V5KSA8ZGNhcm9l
c3RAcmVkaGF0LmNvbT4ACgkQQHHH4dJiacMLkQf+Lt945gRcLEl5fT+VOHydIF33
A8yHyem026z3Wdt9wCTJ1eSd1Y7PB0nOxBoL/CXAP5qf28y5yogHX79ErQN1dWKg
+YrLWAEOCViHuXRh3gGrwtbCElXNvKer1uCicw2BRjPHstzlnPlKfI8MEGfPTjPr
BpgEiRzdZhememBHgLR6fEmu0nz3yxJ7MwPqY89syXaZ8sX82T34AjIC4cA+3jIf
9mcoF296ea/DfMHbusUDOLFpZsZ0+rFVrhvCxie1eqIBzHF/8kiAEwH35aC1kct/
uBv59mEWJqz3WNDoBQrIIf/pmy3Xv3mmsmahCijrelqqD6kkA1t1P6bhjmpuOw==
=BMEF
-----END PGP SIGNATURE-----

**Comment by david-caro** [comment]
It works for me, which distro are you using?

**Comment by david-caro** [comment]
I just found that issue on old pip (using centos default rpm install) , using a newer one upgrading it from pip (pip install --upgrade pip) fixes the issue.

Any suggestion on how to solve it without forcing anyone to upgrade to non-stable release pip?

**Comment by david-caro** [comment]
(non stable in the official distro repos I mean)

**Comment by avi3tal** [comment]
Thanks man, got it!
