### ISSUE TITLE
Failed to install package, any help?

### ISSUE THREAD

**Issue by Sudarshan2018** [david-caro/python-foreman#94]
Failed to install package on windows system
Traceback (most recent call last):
  File "C:\python-foreman-master\python-foreman-master\
setup.py", line 35, in <module>
    'Programming Language :: Python :: 3.4',
  File "C:\ProgramData\Anaconda2\lib\site-packages\setuptools\__init__.py", line
 140, in setup
    return distutils.core.setup(**attrs)
  File "C:\ProgramData\Anaconda2\lib\distutils\core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\setuptools\dist.py", line 370
, in __init__
    k: v for k, v in attrs.items()
  File "C:\ProgramData\Anaconda2\lib\distutils\dist.py", line 287, in __init__
    self.finalize_options()
  File "C:\ProgramData\Anaconda2\lib\site-packages\setuptools\dist.py", line 529
, in finalize_options
    ep.load()(self, ep.name, value)
  File "build\bdist.win-amd64\egg\autosemver\__init__.py", line 176, in distutil
s
  File "build\bdist.win-amd64\egg\autosemver\__init__.py", line 125, in distutil
s_autosemver_case
  File "build\bdist.win-amd64\egg\autosemver\packaging.py", line 86, in get_curr
ent_version
RuntimeError: Failed to get package version

**Comment by david-caro** [comment]
Yep, unfortunately windows is not supported, feel free to send any pull request to add the support for it. Thanks for the issue though.
